// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for android - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBBdKV8WGBxzKnCGMUoXYIbWJn18urBr_A',
//     appId: '1:657860341813:web:242a10396e5c0d86ff017c',
//     messagingSenderId: '657860341813',
//     projectId: 'blue-wash-59b99',
//     authDomain: 'blue-wash-59b99.firebaseapp.com',
//     storageBucket: 'blue-wash-59b99.appspot.com',
//     measurementId: 'G-NHXVHV0XMM',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDbKaPY2fu65gF2xYCh7SobV74WMkDuej0',
//     appId: '1:657860341813:ios:67c63aa79a434fb8ff017c',
//     messagingSenderId: '657860341813',
//     projectId: 'blue-wash-59b99',
//     storageBucket: 'blue-wash-59b99.appspot.com',
//     iosBundleId: 'com.example.blueWashWeb',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBBdKV8WGBxzKnCGMUoXYIbWJn18urBr_A',
//     appId: '1:657860341813:web:ace0ce4f17b2c0c6ff017c',
//     messagingSenderId: '657860341813',
//     projectId: 'blue-wash-59b99',
//     authDomain: 'blue-wash-59b99.firebaseapp.com',
//     storageBucket: 'blue-wash-59b99.appspot.com',
//     measurementId: 'G-X2CW2NJGHS',
//   );
// }
